### ISSUE TITLE
Can't run Front-end benchmark

### ISSUE THREAD

**Issue by DjebbZ** [roman01la/uix#11]
The README command `clojure -A:dev:benchmark -m figwheel.main -O advanced -bo benchmark` just produces a javascript. I haven't find a way to actually run the front benchmark. I tried manually with `clojure -A:dev:benchmark -m cljs.main -re node -co benchmark.cljs.edn -m uix.benchmark` without success. How do you do ?

**Comment by roman01la** [comment]
I run a static server from `resources/public` dir. Don't know if there's a way to serve advanced compiled bundle using fighweel or something

**Comment by DjebbZ** [comment]
I found a solution, working on a PR. Just wait a little bit :)
