### ISSUE TITLE
Useless npm dependencies caching for Circe CI ?

### ISSUE THREAD

**Issue by DjebbZ** [roman01la/uix#13]
I'm new to the project, but since uix doesn't need npm at all and doesn't even have a package.json file, some of the stuff in `.circleci/config.yml` are useless. Want a PR ? (I'm in a PR frenzy today)

**Comment by roman01la** [comment]
Yes sure :)

**Comment by DjebbZ** [comment]
(And this maybe the last PR for today, I was lucky enough to find some time to contribute. Looking forward to where you'll push the library, and if I can help just ping me in an issue)

**Comment by roman01la** [comment]
Thanks!
