### ISSUE TITLE
Splitting library into multiple packages

### ISSUE THREAD

**Issue by roman01la** [roman01la/uix#16]
I may use UIx on React Native project soon, but the library is not compatible with multiple render targets at the moment because it directly depends on `react-dom`. The plan is to split UIx into `uix.core`, `uix.dom` and `uix.native` libraries all living in a monorepo here.

**Comment by DjebbZ** [comment]
Yes monorepo please.

**Comment by DjebbZ** [comment]
Oh it's already done, makes code easier to read since each file is smaller.

**Comment by roman01la** [comment]
Done in 8c7ad3179f
