### ISSUE TITLE
Should uix.core.alpha/memoize only be included in Clojurescript

### ISSUE THREAD

**Issue by caleb** [roman01la/uix#19]
Right now `uix.core.alpha/memoize` is compiled in the the Clojure as well as Clojurescript environments:

https://github.com/roman01la/uix/blob/845cf9cb1c9c875aa8976d10a37bfe615ab0ba61/core/src/uix/core/alpha.cljc#L47-L57

I'm getting an error when trying to use macros from uix.core.alpha: "RuntimeException No such namespace: react"

Is there something I'm missing, or is this a bug?

-Caleb

**Comment by roman01la** [comment]
@caleb That's a bug, thanks for reporting. Fixed.
