### ISSUE TITLE
Move files in resources/public to alias in deps

### ISSUE THREAD

**Issue by noonian** [roman01la/uix#2]
Currently, `resources/public` is included in the top-level `:paths` in `deps.edn`. This can cause conflicts with library consumers as it is very common to serve static assets from the classpath. For example, figwheel-main looks for public/index.html on the classpath and picks up the file from uix if included in deps.

Since these files seem to be for development and benchmarking only, I suggest moving them into another resources folder and adding them to the classpath via `:extra-paths` in an alias.

Thanks for the library!

**Comment by roman01la** [comment]
Good catch, thanks!
