### ISSUE TITLE
Bug in global state recipe

### ISSUE THREAD

**Issue by den1k** [roman01la/uix#22]
`state*` in https://github.com/roman01la/uix/blob/master/core/dev/uix/recipes/global_state.cljc#L9 never changes, instead it remains the first value.

This means the new value `nf` is always compared to the initial value. I hack-fixed this by ignoring the hook state completely and running f on the old and new state as provided by add-watch, like so

```
(defn <sub [f]
  #?(:clj
     nil
     :cljs
     (let [state* (uix/state #(f @db))] ;; <- stale
       (uix/effect!
        (fn []
          (let [id            (random-uuid)
                unsub?        (atom false)
                check-updates (fn [o n]
                                (let [of (f o)
                                      nf (f n)]
                                  (when (and (false? ^boolean @unsub?) (not= nf of))
                                    (-reset! state* nf))))]
            (add-watch db id #(check-updates %3 %4))
            (check-updates nil @db)
            #(do
               (reset! unsub? true)
               (remove-watch db id))))
        [f])
       @state*)))
```

**Comment by roman01la** [comment]
I don't think the whole approach is right, I'd remove the recipe or refactor it to use React's Context. I don't know what is best in React at the moment.

**Comment by caleb** [comment]
I'm glad you made this issue. I noticed this when playing around with UIX in the beginning, but didn't get around to writing up a bug.

I made a `watch-atom` hook like this:

**UPDATE**

**Here is a newer version of the "watch atom" hook that actually updates the `previous-state` ref (the previous version used an effect hook that depended on the atom itself, which doesn't change and thus wasn't re-run even if the contents of the atom changed):**

```clojure
#?(:cljs (defn watch-atom-with [atom f]
           (let [force-render* (uix/state false)
                 value (f @atom)
                 previous-state* (uix/ref value)]

             (uix/with-layout-effect [value f]
                                     (reset! previous-state* value))
             (uix/with-layout-effect [atom f]
                                     (let [watch-key (name (gensym "watch-atom-with"))
                                           check (fn [old new]
                                                   (when (not= old new)
                                                     (swap! force-render* not)))]
                                       (add-watch atom watch-key (fn [_key _ref _old new]
                                                                   (check @previous-state* (f new))))
                                       (check @previous-state* (f @atom))
                                       (fn [] (remove-watch atom watch-key))))
             value)))
```

The logic was influence from the redux-react `useSelector` hook:

https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.js

I've been watching the development of that hook because it faces similar issues that we will when watching atoms.

**Comment by roman01la** [comment]
@caleb Feel free to open a PR

**Comment by caleb** [comment]
Once I use this stuff for a bit longer I will submit a PR. I want to make sure it works correctly.

**Comment by roman01la** [comment]
@den1k Rewrote the recipe, take a look https://github.com/roman01la/uix/commit/da82b5987b27eb4a2d6843e209f2d9f02252ec28

**Comment by den1k** [comment]
It seems like useLayoutEffect could slow down re-renders? 

https://reactjs.org/docs/hooks-reference.html#uselayouteffect

**Comment by roman01la** [comment]
`useLayoutEffect ` part is copied over from react-redux, I think they had reasons for using it instead of normal effect
