### ISSUE TITLE
SSR clojurescript

### ISSUE THREAD

**Issue by jimmyhmiller** [roman01la/uix#24]
Wanted to say first that I love what you are doing with uix. 

I was curious if there was any reason you left out SSR for a clojurescript application. You have the [functions defined for clj, but not cljs](https://github.com/roman01la/uix/blob/0af5529583884af1c0a0aefaa4f4a24983d04237/dom/src/uix/dom/alpha.cljc#L66-L88).

Given what you have in the compiler it seems like you could just use compiler/as-element and the methods in [react-dom/server](https://reactjs.org/docs/react-dom-server.html) to implement those.

Any opposition to that or just haven't done it yet? Thanks again for the great library.

**Comment by roman01la** [comment]
No opposition, you can do it the way you decsribed. I don't want to put this into the code because it will require everyone to depend on react-dom/server, instead maybe a short notice in readme would be fine.

**Comment by jimmyhmiller** [comment]
Sorry for such a late response. `react-dom/server` is already included in the react-dom package. Nothing needs to be added. You can even see this by looking at the cljsjs package description. https://github.com/cljsjs/packages/blob/b0d9f558f92473ab1d7b08b31399e9d86bd178c7/react/build.boot#L64-L71
