### ISSUE TITLE
question :re error-boundary

### ISSUE THREAD

**Issue by den1k** [roman01la/uix#25]
Thanks @roman01la for adding `create-error-boundary`.

I've tried using it and I'm getting confused since there doesn't seem to be a way to recover from an error-state.

For example:

```
(defn child []
  [:h1 {:on-mouse-move #(when (> 0.5 (rand))
                          (throw (js/Error. "Error")))}
   "Everything is fine."])

(def error-boundary
  (core/create-error-boundary
    {:error->state (fn [error] {:error error})
     :handle-catch (fn [error info] (println error))}
    (fn [{:keys [error]} [child]]
      (if error
        error
        child))))

;; somewhere in the app
[error-boundary [child]]
```

How can `error-boundary` ever recover? How can the error-state be removed in the case that new props are available for `child` that might not lead to an error? 
```

**Comment by roman01la** [comment]
How'd you do it in JS?

**Comment by den1k** [comment]
I couldn't get it to work simply. To do so I'd have made a vanilla react component in cljs and passed an `on-error` handler down to error boundary that mutates state in the parent. Then the render logic around `error?` lived in the parent and would get reset by subscribing to the same state the child component receives and only if it changed.

You can see how this is not optimal, since the parent component needs to subscribe to the same state, which has to be global or passed down the tree, as the child.

Error boundary works great for components that error once and are not supposed to re-render. IMO this requirement is rare. More often one would like to let the child possibly re-error on re-render.

Any ideas on how to make this work?

**Comment by roman01la** [comment]
I mean can you provide an example in JavaScript/React of such behavior? Error boundary in UIx is WIP, I've added as much functionality as I need, but happy to extend it if you show me an example where state update is useful.

**Comment by den1k** [comment]
Sure. Here's what I currently use which behaves similarly to uix's `error-boundary`

https://github.com/den1k/zeal/blob/master/src/zeal/ui/views.cljc#L564-L622

In this case the _data renderers_ can throw while parsing the result. However, each eval updates the result so we'd like to check again if it can now be parsed.

**Comment by roman01la** [comment]
I've changed error boundary to accept state atom instead of a value 7fe8329e689, not sure if this solves your problem

**Comment by den1k** [comment]
Thanks @roman01la! This looks like it should work. I'll test it out soon. Closing this for now.
