### ISSUE TITLE
Consider useReducer as impl for state

### ISSUE THREAD

**Issue by alexisvincent** [roman01la/uix#26]
swap! on a `(uix/state initial)` has different semantics to a Clojure atom. two subsequent calls to swap! use the same value, and effectively acts as a reset. 

Any chance this could be moved to be backed by useReducer?

**Comment by roman01la** [comment]
I don't understand what is the problem, an example with comments would be helpful

**Comment by alexisvincent** [comment]
Apologies, I was too quick here. Not actually an issue.

```
  (let [x (uix/state 1)]
    (uix/effect!
     (fn []
       (swap! x inc)
       (swap! x inc))
     [])
    (js/console.log @x))
```

I was expecting the above example to print 1, and then 2, but it does the correct thing and prints 1 and then 3.
