### ISSUE TITLE
Prefix sha not supported, use full sha for uix.core/uix.core

### ISSUE THREAD

**Issue by ava-sig** [roman01la/uix#31]
**Describe the bug**
Quick starting the project, running lein-tools-deps "0.4.5" and adding deps.edn as suggested, I get `clojure.lang.ExceptionInfo: Prefix sha not supported, use full sha for uix.core/uix.core`

**Include minimal repro**
In my project.clj I added:
```
  :plugins [[lein-tools-deps "0.4.5"]]
  :middleware [lein-tools-deps.plugin/resolve-dependencies-with-deps-edn]
  :lein-tools-deps/config {:config-files [:install :user :project]}
```
and in deps.clj : 
```
{:deps {uix.core {:git/url "https://github.com/roman01la/uix.git"
                  :deps/root "core"
                  :sha "{{commit hash}}"}
        uix.dom {:git/url "https://github.com/roman01la/uix.git"
                 :deps/root "dom"
                 :sha "{{commit hash}}"}
        uix.rn {:git/url "https://github.com/roman01la/uix.git"
                :deps/root "rn"
                :sha "{{commit hash}}"}}}
```

**Expected behavior**
It should pull the project from this git repo. Instead I get an error.

**Additional context**
Will look more into this.

**Comment by roman01la** [comment]
You have to put an actual commit sha into deps instead of {{commit hash}} placeholder

**Comment by ava-sig** [comment]
okay, sorry about that, I actually thought some middleware will resolve for the latest commit hash and replace that variable, I now see that it's my job to select a hash. thanks for this quick answer
