### ISSUE TITLE
Trying to js/Fetch via POST

### ISSUE THREAD

**Issue by ava-sig** [roman01la/uix#32]
Hi, I've been using xframe with great satisfaction and I've run into a jam. Looking through the recipes, I can't seem to find a js/Fetch example via POST to be dispatched by a component.
So I tried writing my own:
```
(xf/reg-fx
 :http-post
 (fn [_ [_ {:keys [url form-data on-ok on-failed]}]]
   (let [opts {:method "POST"
               :body form-data
              :headers {:Content-Type "application/json"}}
         ]
     (-> (js/fetch url (bean/->js opts))
         (.then #(if (.-ok %)
                   (.json %)
                   (xf/dispatch [on-failed %])))
         (.then bean/->clj)
         (.then #(xf/dispatch [on-ok %]))))))
```
I think I'm messing up the :body property because method and Content-Type work, but on the server side I get [object Object] and my ring app replies: `Malformed JSON in request body.`. Do I need to do some preprocessing ? form-data is a clojure map.

**Comment by roman01la** [comment]
This question is not related to this repo, but I'll try to answer. You have to serialize the body. So do the following `(-> form-data bean/->js js/JSON.stringify)`.

I'd suggest to post similar questions to #uix Slack channel on Clojurians Slack

**Comment by roman01la** [comment]
As for xframe, be aware that the library is based on Adapton implementation that relies on unbound memoization. This can cause memory consumption issues in apps with long user sessions. I may improve this later.

**Comment by ava-sig** [comment]
thank you for your answer, I assumed as much that it won't pertain to xframe. Thanks regardless.
Also, thank you for addressing issues with memory consumption.
