### ISSUE TITLE
Feature request: optional user-specified `format-display-name`

### ISSUE THREAD

**Issue by darwin** [roman01la/uix#35]
I'd like to have a way how to set custom `format-display-name` (in my dev builds).

My namespaces are quite long and this would be a centralized way how to strip common prefix from component names. Also one could apply app-specific knowlege on forming component names.

**Comment by darwin** [comment]
Not sure if React does not support something like this globally. My google-fu didn't reveal anything. Happy to learn about it.

**Comment by roman01la** [comment]
I don't think React can do that. But we could do it similarly to how a custom printing function can be set in cljs `(set! *print-fn* f)`.

**Comment by darwin** [comment]
Sounds good. I already can hack it in my init code similar to [this](https://github.com/binaryage/cljs-react-three-fiber/blob/4bda0665ab2e616a7d3f060e09c252bf780008d8/examples/src/hacks/uix/hacks.cljs#L24).

But I would rather see officially supported way. Do you want me to go ahead and prepare a PR?

**Comment by roman01la** [comment]
Yes a PR would be great. Thanks 🙌
