### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by den1k** [roman01la/uix#38]
**Describe the bug**

Hi Roman! 

I'm moving my component library `root` from reagent to UIX to allow for SSR. In vain I've spent all of yesterday trying to get make my example app to be reactive as it is in reagent.

For some background, root is a recursive data-dispatch-based component rendering library. Given a `lookup` function and a `root-id` it will resolve a datom to its component and it with equally resolved child-components. This enables it to create reactive views on data in any form. To change the arrangement of the components one only needs to mutate the data returned from `lookup`, i.e. no need to sprinkle conditionals all over component code. For example, root could work very well to implement a AST based code editor or to implement a unstructured document editor similar to notion.so.

At one point I've had it set up with xframe dispatches and subscriptions, at another with `<sub` that you helped me implement months ago in my project [Zeal](https://github.com/den1k/zeal/blob/a43a47963606da6013c8a08f8579fb0b8c470f72/src/zeal/ui/state.cljc#L29). While it works with reagent, all attempts trying to make it work with UIX resulted in `Uncaught Error: Rendered more hooks than during the previous render...`

At this point I'm out of ideas ¯\_(ツ)_/¯ I'd appreciate any help! Root will be open sourced soon and I hope it will be a useful and powerful library for the Clojure community. Before doing so I just want to make sure I have a somewhat robust API and real project (which I'm working on) to go along with it.

**Include minimal repro**
I added you as a contributor.
https://github.com/den1k/root/blob/master/examples/debug/core.cljs
`$ yarn watch`
http://localhost:8700/

Comment reagent out for uix:
https://github.com/den1k/root/blob/master/examples/debug/core.cljs#L39-L40

**Expected behavior**
With reagent clicking the button updates the the component. Using uix with a simple lookup nothing happens. Using uix with `<sub` or `xf/dispatch` + `xf/sub` breaks the app while throwing `Uncaught Error: Rendered more hooks than during the previous render.`

🙏️

**Comment by roman01la** [comment]
Hey. The error you are getting from React means that you have a component that changes the number of hooks it instantiates between updates. This is not allowed in React, unfortunately. You can't programmatically instantiate an arbitrary number of hooks. I'm not sure where this happens in your code, bit that is what the error means.

**Comment by den1k** [comment]
Could it be that I get this error because parent components reinstantiate child components dynamically on every update?
Meaning that previous hooks have not been torn down when new ones instantiate?

**Comment by roman01la** [comment]
No, hooks are alive only per component's lifetime. Do you use any hooks in code? You either create them conditionally during component's lifetime or maybe calling component function directly instead of declaring it as a Hiccup `(component) vs [component]`?

**Comment by den1k** [comment]
I tried `(component)` vs `[component]` in vain.
The only function that creates hooks (for all components is `lookup`
https://github.com/den1k/root/blob/master/examples/debug/core.cljs#L42-L44
and it's only used in one place, the resolver
https://github.com/den1k/root/blob/master/src/root/impl/resolver.cljc#L141

**Comment by roman01la** [comment]
It's hard to tell without digging into the code, there are lots of nested calls, but here you create a components as Hiccup https://github.com/den1k/root/blob/12a9be330d7efc12cd44da674a55e1617320c3c1/examples/debug/core.cljs#L70 and here you are calling the function directly https://github.com/den1k/root/blob/master/src/root/impl/resolver.cljc#L147 maybe the problem is somewhere there

**Comment by den1k** [comment]
Романе, дякую! You're right. It works! That oversight on my part put me close to giving up.

Thanks again for having a look! Can't wait to open source this.
Closing this issue!

- D

**Comment by den1k** [comment]
Fix: https://github.com/den1k/root/commit/430587770b7cb7fb7b9b9e949f8c7e4f95ae4519#diff-07b6c04ab02db120472457642fbbfcfcR147

**Comment by roman01la** [comment]
Great! Glad I helped.
