### ISSUE TITLE
Multiple db's in xframe

### ISSUE THREAD

**Issue by den1k** [roman01la/uix#43]
**Is your feature request related to a problem? Please describe.**
`xframe.core.alpha` defines 1 `db` and 1 `subs-registry` which means if one wanted to render multiple apps using xframe side by side they'd have to share one db.

https://github.com/roman01la/uix/blob/master/core/src/xframe/core/alpha.cljc#L31

**Describe the solution you'd like**
Support for multiple db's in xframe

**Describe alternatives you've considered**
Multiple apps sharing one db by using a keyword as a lookup namespace for an app. This is possible but feels hacky since separate apps should truly be separate.

**Comment by roman01la** [comment]
Something like this could work
```clojure
(ns app.db)

(xf/reg-db :app/db (atom {}))

(def reg-sub
  (xf/create-reg-sub :app/db))

(def reg-event-db
  (xf/create-reg-event-db :app/db))

(ns app.core)

(app.db/reg-sub ...)
```

**Comment by den1k** [comment]
@roman01la this isn't in xframe, yet, right? Just tried to go ahead and use this 😄️

**Comment by den1k** [comment]
@roman01la is the above possible already? I'm struggling to figure out a setup with multiple DB's

**Comment by nrfm** [comment]
this is the feature that would make switch over to uix. is the feature working ? thanks.

**Comment by roman01la** [comment]
not gonna work on this anytime soon
