### ISSUE TITLE
xframe <sub __REACT_DEVTOOLS_GLOBAL_HOOK__ is not defined

### ISSUE THREAD

**Issue by crofty** [roman01la/uix#45]
**Describe the bug**
I'm getting the error: `ReferenceError: __REACT_DEVTOOLS_GLOBAL_HOOK__ is not defined` in the devtools console.

I'm using the latest commit 6e06ec216e9fed86d1875877800d468f6d099825

I think the error is coming from https://github.com/roman01la/uix/blob/master/core/src/xframe/core/alpha.cljc#L127

**Include minimal repro**
Evaluating `js/__REACT_DEVTOOLS_GLOBAL_HOOK__` in the cljs repl throws the same error:
```
#object[ReferenceError ReferenceError: __REACT_DEVTOOLS_GLOBAL_HOOK__ is not defined]
	 (<NO_SOURCE_FILE>)
```

Using `(exists? js/__REACT_DEVTOOLS_GLOBAL_HOOK__)` returns `false`.  I notice that the cljs files use the `exists?` check before referring to `__REACT_DEVTOOLS_GLOBAL_HOOK__`.

I tried modifying the `<sub` macro to use exists, but I kept tripping up on the macro syntax.

**Comment by den1k** [comment]
I can repro this under optimizations `simple`. This fails because the variable was never defined. I think the fix is to use a lookup instead, i.e. `(some? js/window.__REACT_DEVTOOLS_GLOBAL_HOOK__)`

**Comment by roman01la** [comment]
Thanks for investigating this. Feel free to submit a PR.
