### ISSUE TITLE
Unable to render id when applied as part of attribute map

### ISSUE THREAD

**Issue by JoshHarrington** [roman01la/uix#46]
**Describe the bug**
There seems to be a difference in the way that elements are rendered between clj and cljs. In clj when an id is applied to an element as part of an attribute map that id is not rendered out. In cljs the id does get rendered as expected.

If the id is applied in css selector type format eg `div#id` the the id does get rendered out in both clj and cljs.

**Include minimal repro**
1. Example 1 - id applied with # format to element tagname. 
In a clj (or cljc) file add the input line and send it to your clj REPL to see the element rendered as a string with an id attribute.
Input:
```(uix.dom.alpha/render-to-string [:div#id "hi"])```
Output:
```"<div id=\"id\">hi</div>"```
 ✅ Correct output

2. Example 2
Add the following input line to a clj (or cljc) file and send to REPL
Input:
```(uix.dom.alpha/render-to-string [:div {:id "id"} "hi"])```
Output:
```"<div>hi</div>"``` 
👎 Unexpected output

**Expected behavior**
I was expecting the same output for both examples, so that the id applied to an attribute map for an element would get rendered and not ignored.

**Additional context**
Nope! 

Thanks 👍

**Comment by roman01la** [comment]
Fixed. Thanks!
