### ISSUE TITLE
Bundle size?

### ISSUE THREAD

**Issue by DjebbZ** [roman01la/uix#5]
I'm very curious about the final Javascript bundle size. Did you compare a simple app written with Reagent and/or Rum vs UIx? I'd love to know the difference.

**Comment by roman01la** [comment]
Here's quick results on TodoMVC

| lib | size | gzip |
|---|---    |---     |
| rum | 254KB | 70KB |
| reagent | 269KB | 74KB |
| uix | 277KB | 81KB |

UIx is larger because it includes `cljs.loader` fore code-splitting which is using Closure's module manager that is a global thing that can't be DCEd

Excluding `cljs.loader` results in `234KB`, and `65KB` gzip

Not a big deal IMO, but I'm gonna decouple that so my inner programmer stays calm

**Comment by roman01la** [comment]
Done in bc16a6a1bc0d3, keep going with those questions :)

**Comment by DjebbZ** [comment]
Something I don't understand: Is UIx _requiring_ code splitting? Or it's just your examples that used the feature?

**Comment by roman01la** [comment]
No it's not required. But there's a useful macro to load React components as Closure's modules on-demand. The macro hides an unnecessary bolierplate and requires cljs.loader, but since you'd use it anyway when working with code splitting I think it's safe to not require it in uix.

**Comment by DjebbZ** [comment]
Yes, I know about the boilerplate, and indeed it seems your code was just a simple passthrough. I don't understand the new version from commit linked above but that's ok. At least it's good to know that you support React code splitting out of the box.

**Comment by DjebbZ** [comment]
Oh, and by the way happy to see UIx bundle already smaller than Rum and Reagent. Do you support only functional component? Do you generate code that look like functional or class-based React components?

**Comment by roman01la** [comment]
Only functional components as regular functions, no classes. At runtime every component is wrapped into React.memo that performs shouldComponentUpdate optimization on functional components.

**Comment by DjebbZ** [comment]
Function over classes: I like. Less code to ship, and they support modern
features like hooks better.
React.memo everywhere: not sure I like. The [React docs](https://reactjs.org/docs/react-api.html#reactmemo) say that it makes
performance better _in some cases_, which is logical since memoization
always has a cost of comparing values. Furthermore React.memo let users
provide their own memoization function and your design prevents customizing
it. And as a last point, React.memo uses [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is)
which doesn't not fit Clojure's equality semantics, so it may lead to
incorrect results. There was a discussion about it in [hx repo](https://github.com/Lokeh/hx/issues/39) (you participated it!). So are you
sure it's a good choice? Wouldn't it be better to leave the door open?
In the end I think it's better to leave the room open.

**Comment by roman01la** [comment]
That discussion is a bit different, but anyway. `React.memo` in UIx is using Clojure's equality semantics. I don't actually have any evidence whether it makes updates slower or faster. So far I haven't seen problems with it in both UIx and Reagent (which is doing it by default as well, [see](https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/component.cljs#L174-L189)). I'm open to change this once there's a strong evidence.

**Comment by DjebbZ** [comment]
Agree with the need for evidence. But what if I have a custom data-type for which I want to provide my own comparator? Wouldn't it be more modular and better to provide a custom React.memo maybe, or just a UIx-blessed comparator and leave components as they are?

**Comment by DjebbZ** [comment]
And sorry for shifting the discussion

**Comment by roman01la** [comment]
I'm not sure how often people have weird things in Clojure, so I'd wait for someone to actually have this problem and then maybe address this in UIx.

**Comment by DjebbZ** [comment]
It happened to us with Rum and took _days_ of debugging. Basically a list component was first rendered with a vector of ~100 maps, then re-rendered with a different vector of ~100 maps, the difference being that only one element around the end of the vector would change. ClojureScript's `=` for vector of maps ends up comparing each map one by one, and for each map each key and value. It completely hanged the browser. So we implemented a custom shouldComponentUpdate. This is the kind of cases where `=` is not you want.

**Comment by DjebbZ** [comment]
My point is that as long as I can easily override the default comparison and/or just not use React.memo I'm ok with the design.

**Comment by roman01la** [comment]
My thinking is that having `React.memo` on by default helps more often than it's not in Clojure, but for such cases as yours I don't yet know how to make it optional or configurable and keep components as pure functions instead of a macro with custom syntax. I also don't want components with `React.memo` turned off by default, because wrapping components is annoying especially because in Clojure you'd use it more often than in JS. Another thing is that Hiccup interpretation has its cost and memoization helps here as well.

**Comment by roman01la** [comment]
Let's move discussion to #7

**Comment by roman01la** [comment]
Should we close this issue?

**Comment by DjebbZ** [comment]
Sure
