### ISSUE TITLE
Support nested element creation

### ISSUE THREAD

**Issue by SevereOverfl0w** [roman01la/uix#51]
**Describe the solution you'd like**

Reagent describes a nested syntax to define nested elements, I noticed it wasn't supported in UIx.

https://reagent-project.github.io/news/news051.html

**Comment by roman01la** [comment]
I don't like this tbh and never used and seen anyone using this syntax. I'd like to not have this in uix.

**Comment by SevereOverfl0w** [comment]
Feel free to close, not passionate about it.

**Comment by roman01la** [comment]
Thanks!
