### ISSUE TITLE
Follow up on #45

### ISSUE THREAD

**Issue by den1k** [roman01la/uix#55]
**Describe the bug**
Related to #45 
While browsers without devtools installed  don't throw an error anymore, I noticed that in builds with `:optimizations :none` use of `<sub` macro does not result in re-renders even though state is updated. It does work in `:optimizations :advanced`.

One difference between `:none` and `:advanced` optimizations the value of `goog.DEBUG` which `<sub` checks for here: https://github.com/roman01la/uix/blob/32238d6ee783eef51f0c968b59c49caaeabaef44/core/src/xframe/core/alpha.cljc#L125-L130

Following from that `goog.DEBUG` being true and absence of devtools resuts in the return of `(~get-state-sym)` which does not cause a re-render.

While this may be the crux of the bug, I also fail to understand how existence of both goog.DEBUG and devtools play into the `<sub` macro? Shouldn't all cases in cljs return the subscription and all clj cases return the state regardless of other variables?

**Include minimal repro**
Try [this recipe](https://github.com/roman01la/uix/blob/32238d6ee783eef51f0c968b59c49caaeabaef44/core/dev/uix/recipes/global_state.cljc) with no compiler optimizations and react devtools not installed (incognito tab).

**Expected behavior**
`<sub` to return subscriptions clojurescript and state in clojure.

**Comment by codeasone** [comment]
> While browsers without devtools installed don't throw an error anymore, I noticed that in builds with :optimizations :none use of <sub macro does not result in re-renders even though state is updated. It does work in :optimizations :advanced.

I'm seeing this too and it's blocking my development workflow atm.

**Comment by roman01la** [comment]
Should be fixed in eee1cc9
