### ISSUE TITLE
Context doesn't work on JVM with Hiccup syntax

### ISSUE THREAD

**Issue by crofty** [roman01la/uix#66]
I asked about this on Slack but I'm also opening an issue as it may help others and it allows me to track it.

**Describe the bug**
Context doesn't work on the JVM when using Hiccup syntax for calling components.

**Include minimal repro**
```.clj
(uix/defcontext *ctx*)

(defn foo []
  [:div (uix/context *ctx*)] )

(defn bar []
  (uix/context-provider [*ctx* 1]
    [foo]))

(uixc/render-to-string [bar])
;; => "<div>Unbound: *ctx*</div>"
```

**Expected behavior**
```
"<div>1</div>"
```

Changing `[foo]` from the Hiccup syntax to a regular function call `(foo)` sidesteps the issue but means Hiccup syntax can't be used.

**Comment by roman01la** [comment]
resolved in #67
