### ISSUE TITLE
Component memoization by default?

### ISSUE THREAD

**Issue by roman01la** [roman01la/uix#7]
Continuing discussion here. Started at https://github.com/roman01la/uix/issues/5#issuecomment-495377222

**Comment by roman01la** [comment]
> My thinking is that having React.memo on by default helps more often than it's not in Clojure, but for such cases as yours I don't yet know how to make it optional or configurable and keep components as pure functions instead of a macro with custom syntax. I also don't want components with React.memo turned off by default, because wrapping components is annoying especially because in Clojure you'd use it more often than in JS. Another thing is that Hiccup interpretation has its cost and memoization helps here as well.

@DjebbZ

**Comment by DjebbZ** [comment]
My take is that "annoying but possible" is better than "nice in most cases, otherwise f*** up with no work-around". I would argue that developer ergonomics should come after correctness.

**Comment by roman01la** [comment]
Yeah I agree. Still have to think how it could look like. The most straightforward approach is to have `memo` fn that uses Clojure's `=` by default, but also takes a custom comparator.

```clj
(defn button [attrs child]
  [:button attrs child])

(def button* (uix/memo button))

(def button-2 (uix/memo button) custom-comp)
```

**Comment by roman01la** [comment]
@DjebbZ Sketched out possible API here 2d99d0d85d2204, I think that should be good enough?

**Comment by DjebbZ** [comment]
Exactly the kind of API I was thinking. It makes it easy to opt out of
memoization by providing `(constantly true)`, and one can use React.memo,
Clojure's `=` or anything else. Approved 👍

**Comment by roman01la** [comment]
In fact when you don't want memoization you simply don't use uix/memoize, and when it's used default comparator will be Clojure's = unless a custom one is provided

**Comment by DjebbZ** [comment]
You're right, I'm stupid 😅
