### ISSUE TITLE
Portal Demo should use LayoutEffect for getting dom node

### ISSUE THREAD

**Issue by zerg000000** [roman01la/uix#71]
**Describe the bug**
Portal Demo should use LayoutEffect for getting dom node

**Include minimal repro**
currently, demo query the dom node in rendering function which break the purity of rendering function.

I try to follow this example
https://blog.logrocket.com/build-modal-with-react-portals/

end up having this code
```clojure
(let [dom (uix/state nil)]
    (uix/layout-effect!
     (fn []
       (let [ele (.getElementById js/document wrapper-id)]
         (when ele
           (reset! dom ele))))
     [wrapper-id])
    (when-let [node @dom]
      (dom/create-portal child node)))
```

**Expected behavior**
Demo should show a common practice way to use the API, since people learn by example.

**Additional context**
..

**Comment by roman01la** [comment]
feel free to open a PR
