### ISSUE TITLE
Portal API enhancement suggestion

### ISSUE THREAD

**Issue by DjebbZ** [roman01la/uix#8]
Me again :)

The current API (at least in the popup recipe) suggests using either a keyword for the CSS selector or a DOM node. The problem I see with CSS as a Clojure keyword is that they give only a tiny subset of what's possible as opposed to normal CSS selectors (as strings). Ex: How do you do "aside .item:first-child" with a keyword? Should it accept CSS selectors as strings instead of keywords?

**Comment by roman01la** [comment]
Indeed string selector would be good as well, but not replacing keyword, just adding a new type of a value.

**Comment by DjebbZ** [comment]
What's the value of using keywords ?

**Comment by roman01la** [comment]
I like keywords :) Just personal preference. I'm also writing CSS using keywords, both keys and values.

**Comment by DjebbZ** [comment]
It seems you're just calling `(name keyword)` at the end.

PS: Sorry for opening issues and commenting a lot, I write as I go through the code base.

**Comment by DjebbZ** [comment]
Ok, I get it. It already supports string in the end. Thanks!

**Comment by roman01la** [comment]
No worries about opening issues, in fact it helps me to understand what should be done different and also thanks to you the library already has smaller bundle size and faster SSR :)

**Comment by DjebbZ** [comment]
You're welcome :)
